project:
  type: website

website:
  title: "Navdeep Rana"
  navbar:
    left:
      - href: index.qmd
        text: Home
      # - href: research.qmd
      #   text: Research
      - cv.qmd
      - publications.qmd
      # - blog/index.qmd

format:
  html:
    theme:
      - cosmo
      - theme.scss
    css: styles.css
    toc: true
    code-copy: true
    code-overflow: wrap
    other-links:
      - text: Google scholar
        href: https://scholar.google.com/citations?user=0kxzpUUAAAAJ
      - text: ORCID
        href: https://orcid.org/0000-0002-4432-3982



